### ISSUE TITLE
Can it be used as a CLI

### ISSUE THREAD

**Issue by amimas** [jonschlinkert/handlebars-lint#2]
This seems interesting but I am not sure how to use it. I'm not writing any tools. I have some handlebars template files in my project that is used for building an html file. I want to lint these templates. But, how do I run it from my terminal? What is the command? Or, is this intended to be used programmatically?

**Comment by doowb** [comment]
> is this intended to be used programmatically?

Yes, because a [context](https://github.com/jonschlinkert/handlebars-lint#example) is required to be passed in. Otherwise, you'll just get warnings that everything is missing from your context.

You can use this along with what you're using to build the html file to pass the handlebars template contents and your context through the linter first, then build your html file.

I'm going to close this issue since it's a question, but feel free to continue asking here if you have another question.

**Comment by amimas** [comment]
Thanks for the quick reply. I didn't realize this could be used as a helper for handlebars. I'm using the following handlebars-cli for building html pages from the handlebars templates.

https://github.com/keithamus/hbs-cli

But, I'm getting an error message when passing this as a helper.

```sh
$ hbs --helper handlebars-layouts --helper handlebars-lint --partial "src/templates/*" --partial "build/*" src/pages/* --output build
WARNING: /Users/amimas/my-project/node_modules/handlebars-lint/index.js does not export a 'register' function, cannot import
```

**Comment by doowb** [comment]
It's not a handlebars helper.
You'll have to use something else, or write a javascript file that's similar to the examples in the README.

I'm not familiar with `hbs-cli`, so I'm not sure how it handles loading the partials, helpers, and data used to build the context, but you can try something simple with a script like this:

```js
const fs = require('fs');
const path = require('path');

// Using @folder/readdir to simplify reading in partials and pages
const readdir = require('@folder/readdir');
const lint = require('handlebars-lint');

// utility to read partial names
const readPartials = dir => {
  return readdir.sync(dir, { objects: true }).map(file => {
    return path.basename(file.name, path.extname(file.name));
  });
};

// utility to load pages
const loadPages = dir => {
  return readdir.sync(dir, { objects: true }).map(file => {
    file.contents = fs.readFileSync(file.path);
    return file;
  });
};

const partials = [...readPartials('src/templates'), ...readPartials('build')];
const pages = loadPages('src/pages');

const context = {
  helpers: ['handlebars-layouts', 'some-other-helper'],
  partials
};

for (let page of pages) {
  console.log(`Page: ${page.path}`);
  console.log(lint(page.contents.toString(), { context }));
  console.log();
}
```

I think this will work, I didn't try running it, but I used the directories you specified in your glob patterns.
If you name the file `lint.js`, then you would run `node lint.js`.

**Comment by amimas** [comment]
Thanks for the suggestion and the code snippet. I'll try it out.
